export const CUISINES = [
  "Pretzel",
  "Cake",
  "Bread",
  "Appetizers",
  "Congee",
  "Arabian",
  "Allergy friendly",
  "Bakery",
  "Swedish",
  "Alcohol",
  "New american",
  "Donut",
  "French",
  "Bistro",
  "Deli",
  "Asian fusion",
  "Charcuterie",
  "Frozen food",
  "Grocery",
  "Brazilian",
  "24 hours",
  "Acai",
  "Afghan",
  "African",
  "American",
  "Asian",
  "Australian",
  "Bacon",
  "Bar food",
  "Bbq",
  "Beef",
  "Belgian",
  "Bento",
  "Biryani",
  "Breakfast and brunch",
  "British",
  "Bubble tea",
  "Burger",
  "Cafe",
  "Canadian",
  "Candy",
  "Cantonese",
  "Caribbean",
  "Chili",
  "Chinese",
  "Coffee and tea",
  "Colombian",
  "Comfort food",
  "Couscous",
  "Cuban",
  "Cupcake",
  "Cured meat",
  "Curry",
  "Custard",
  "Dessert",
  "Dim sum",
  "Diner",
  "Dinner",
  "Dominican",
  "Dosa",
  "Drink",
  "Dutch",
  "Eastern european",
  "Eggs",
  "English",
  "Ethiopian",
  "European",
  "Family meals",
  "Fast food",
  "Filipino",
  "Fish and chips",
  "German",
  "Gluten free",
  "Gourmet",
  "Greek",
  "Grill",
  "Halal",
  "Hawaiian",
  "Healthy",
  "Hibachi",
  "Home and personal care",
  "Hotpot",
  "Ice cream and frozen yogurt",
  "Indian",
  "Indian curry",
  "Indonesian",
  "Irish",
  "Italian",
  "Jamaican",
  "Japanese",
  "Japanese curry",
  "Jewish",
  "Juice and smoothies",
  "Kebabs",
  "Kids friendly",
  "Korean",
  "Korean bbq",
  "Kosher",
  "Lasagne",
  "Late night",
  "Latin american",
  "Latin fusion",
  "Lebanese",
  "Liquor",
  "Lobster",
  "Low calorie",
  "Low carb",
  "Mac and cheese",
  "Malaysian",
  "Matcha",
  "Mediterranean",
  "Mexican",
  "Middle eastern",
  "Milkshake",
  "Modern asian",
  "Modern australian",
  "Modern european",
  "Modern french",
  "Moroccan",
  "Nepalese",
  "New canadian",
  "New mexican",
  "Noodles",
  "North indian",
  "Northeastern thai",
  "Northern thai",
  "Organic",
  "Oysters",
  "Paella",
  "Pakistani",
  "Pasta",
  "Pastry",
  "Persian",
  "Peruvian",
  "Pharmacy",
  "Pho",
  "Pie",
  "Pizza",
  "Poke",
  "Polish",
  "Pollo",
  "Portuguese",
  "Poutine",
  "Pub",
  "Ramen",
  "Raw",
  "Ribs",
  "Rolls",
  "Rum",
  "Russian",
  "Salad",
  "Salmon",
  "Sandwich",
  "Sashimi",
  "Seafood",
  "Shanghai",
  "Shawarma",
  "Singaporean",
  "Snacks",
  "Soul food",
  "Soup",
  "South african",
  "South american",
  "South asian",
  "South east asian",
  "South indian",
  "Southern",
  "Southern thai",
  "Spanish",
  "Spirits",
  "Sri lankan",
  "Street food",
  "Sushi",
  "Sweets",
  "Taiwanese",
  "Tapas",
  "Tex mex",
  "Thai",
  "Traditional american",
  "Turkish",
  "Udon",
  "Vegan",
  "Vegan friendly",
  "Vegetarian",
  "Vegetarian friendly",
  "Vietnamese",
  "Western",
  "Wine",
  "Wings",
  "Wrap",
  "Yakiniku",
  "Yakitori",
  "Sydney nsw?mod=selectlanguage&ps=1",
  "Fettuccine alfredo",
  "Sopes",
  "Roast beef bowl",
  "Arancini",
  "Pudding",
  "Arroz con leche",
  "Apple crumble",
  "Baby back ribs",
  "Gyro",
  "American pizza",
  "Creme brulee",
  "Carbonara",
  "Chicken bowl",
  "Thai fried rice",
  "Calzones",
  "Avocado salad",
  "Brownies",
  "Chicken burger",
  "Chicken gyro",
  "Banana split",
];
