
export const LOCATIONS = {
    SYDNEY: { LONGITUDE: 151.2093, LATITUDE: -33.8688 }
}

export const DEFAULT_ZOOM = 12;

export const DEFAULT_LONGITUDE = LOCATIONS.SYDNEY.LONGITUDE;

export const DEFAULT_LATITUDE = LOCATIONS.SYDNEY.LATITUDE;
